apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: sample

bases:
- ../../base

namePrefix: prod-

patches:
- path: deployment.yaml
- path: hpa.yaml
- patch: |-
    - op: replace
      path : /spec/tls/0/hosts/0
      value: prod.example.com
    - op: replace
      path : /spec/rules/0/host
      value: prod.example.com
  target:
    kind: Ingress
    name: sample

images:
  - name: registry/sample
    newTag: v1.0.1