apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp
spec:
  rules:
    - host: "darko3.prodyna.wtf"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: myapp
                port:
                  number: 80
  tls:
    - hosts:
        - "darko3.prodyna.wtf"
      secretName: myapp-tls
