apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-data
spec:
  storageClassName: "default" # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
