apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-data
spec:
  storageClassName: "azurefile" # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
