apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: darkocr.azurecr.io/sample:1.1
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: http
              path: /health
            initialDelaySeconds: 5
            failureThreshold: 1
            successThreshold: 3
            periodSeconds: 2
          envFrom:
            - configMapRef:
                name: demo
            - secretRef:
                name: demo
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: 82m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          volumeMounts:
            - name: static
              mountPath: /static
              readOnly: true
            - name: demo-config
              mountPath: /config
              readOnly: true
      volumes:
        - name: demo
          persistentVolumeClaim:
            claimName: demo-rwx
        - name: static
          configMap:
            name: demo-static
        - name: demo-config
          configMap:
            name: demo
