apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
spec:
  rules:
    - host: "darko.prodyna.wtf"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: demo
                port:
                  name: http
