apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: sample

resources:
  - clusterissuer.yaml
  - deployment.yaml
  - hpa.yaml
  - ingress.yaml
  - service.yaml
  - serviceaccount.yaml

configMapGenerator:
- name: sample-config
  env: conf.properties
