image:
  pullPolicy: Always
ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-traefik
  tls:
  - hosts:
    - example.com
    secretName: sample-tls
  hosts:
    - host: example.com
      paths:
        - path: /
          pathType: ImplementationSpecific

env:
  - name: "OPENTELEMETRY_ENDPOINT"
    value: "opentelemetry-collector.observability:4317"
  - name: REDIS_ENABLED
    value: "false"
  - name: REDIS_ENDPOINT
    value: "redis-master.redis:6379"
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
serviceMonitor:
  enabled: false