apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sample.fullname" . }}
  labels:
    {{- include "sample.labels" . | nindent 4 }}
data:
{{- range .Values.staticFiles }}
  {{ .filename }}: |
{{ .content | nindent 4 }}
{{- end }}
