{{- if .Values.persistentVolumeClaim.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sample.fullname" . }}
  labels:
    {{- include "sample.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistentVolumeClaim.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.size | quote }}
  {{- if .Values.persistentVolumeClaim.storageClassName }}
  storageClassName: {{ .Values.persistentVolumeClaim.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.size | quote }}
{{- end }}
