apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  labels:
    app: sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: sample
        # Please replace with your own image form the ACR
        image: dkrizicgwcdevacrmain.azurecr.io/sample:1.1
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: sampleconfig
          - secretRef:
              name: sampledb
        env:
          - name: REDIS_ENABLED
            value: "false"
          - name: REDIS_ENDPOINT
            value: "redis-master.redis:6379"
        ports:
        - containerPort: 8000
          name: web
        - containerPort: 8001
          name: metrics
        - containerPort: 8002
          name: health
        readinessProbe:
          httpGet:
            path: /health
            port: web
          # needs to return http status code 200 .. <=399
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
#        volumeMounts:
#          - name: static
#            mountPath: /static
#            readOnly: true
#          - name: data
#            mountPath: /data
#          - name: shared
#            mountPath: /shared
#      volumes:
#        - name: static
#          configMap:
#            name: samplestatic
#        - name: data
#          persistentVolumeClaim:
#            claimName: sampledata
#        - name: shared
#          persistentVolumeClaim:
#            claimName: sampleshared
---
apiVersion: v1
kind: Service
metadata:
  name: sample # http://sample.default
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: web
  selector:
    app: sample
  sessionAffinity: None
  type: ClusterIP
